### ISSUE TITLE
Siren's do not work on all models.

### ISSUE THREAD

**Issue by Proportionality** [FiveM-Scripts/ELS-FiveM#2]
Here is my issue;

ELS will not work on all models, however, it works on the FBI2, our 2016 FPIU. If I move the 2016 FPIU to another slot, it then works. 

All of our models are custom.

**Comment by plunkettscott** [comment]
VCF files have been implemented for this purpose, and are currently being tested. Possibly resolved.

**Comment by ghermans** [comment]
Does this issue still exists @ejb1123 ?
